import type { RoleId } from '~/src/shared/config/roles'

export interface ChampionData {
  id: string
  name: string
  title: string
  roles: RoleId[]
}

export const CHAMPIONS: ChampionData[] = [
  { id: 'Aatrox', name: 'Атрокс', title: 'Клинок Даркинов', roles: ['top'] },
  { id: 'Ahri', name: 'Ари', title: 'Девятихвостая лиса', roles: ['mid'] },
  {
    id: 'Akali',
    name: 'Акали',
    title: 'Разбойница Кинку',
    roles: ['mid', 'top'],
  },
  { id: 'Akshan', name: 'Акшан', title: 'Страж-бунтарь', roles: ['mid'] },
  {
    id: 'Alistar',
    name: 'Алистар',
    title: 'Минотавр',
    roles: ['support'],
  },
  {
    id: 'Amumu',
    name: 'Амуму',
    title: 'Печальная мумия',
    roles: ['jungle', 'support'],
  },
  {
    id: 'Anivia',
    name: 'Анивия',
    title: 'Криофеникс',
    roles: ['mid'],
  },
  { id: 'Annie', name: 'Энни', title: 'Тёмное дитя', roles: ['mid'] },
  {
    id: 'Aphelios',
    name: 'Афелий',
    title: 'Оружие верных',
    roles: ['adc'],
  },
  { id: 'Ashe', name: 'Эш', title: 'Лучница льдов', roles: ['adc'] },
  {
    id: 'AurelionSol',
    name: 'Аурелион Сол',
    title: 'Создатель звёзд',
    roles: ['mid'],
  },
  { id: 'Azir', name: 'Азир', title: 'Император песков', roles: ['mid'] },
  { id: 'Bard', name: 'Бард', title: 'Вечный странник', roles: ['support'] },
  {
    id: 'Blitzcrank',
    name: 'Блицкранк',
    title: 'Великий паровой голем',
    roles: ['support'],
  },
  { id: 'Brand', name: 'Бранд', title: 'Горящая месть', roles: ['support'] },
  {
    id: 'Braum',
    name: 'Браум',
    title: 'Сердце Фрельйорда',
    roles: ['support'],
  },
  {
    id: 'Caitlyn',
    name: 'Кейтлин',
    title: 'Шериф Пилтовера',
    roles: ['adc'],
  },
  {
    id: 'Camille',
    name: 'Камилла',
    title: 'Стальная тень',
    roles: ['top'],
  },
  {
    id: 'Cassiopeia',
    name: 'Кассиопея',
    title: 'Змеиное объятие',
    roles: ['mid'],
  },
  {
    id: 'Darius',
    name: 'Дариус',
    title: 'Длань Ноксуса',
    roles: ['top'],
  },
  { id: 'Diana', name: 'Диана', title: 'Презрение луны', roles: ['jungle'] },
  {
    id: 'Draven',
    name: 'Дрейвен',
    title: 'Славный палач',
    roles: ['adc'],
  },
  {
    id: 'Ekko',
    name: 'Экко',
    title: 'Мальчик, разбивший время',
    roles: ['jungle', 'mid'],
  },
  {
    id: 'Elise',
    name: 'Элиза',
    title: 'Королева пауков',
    roles: ['jungle'],
  },
  {
    id: 'Ezreal',
    name: 'Эзреаль',
    title: 'Блудный исследователь',
    roles: ['adc'],
  },
  {
    id: 'Fiora',
    name: 'Фиора',
    title: 'Гранд-дуэлянтка',
    roles: ['top'],
  },
  { id: 'Fizz', name: 'Физз', title: 'Морской хитрец', roles: ['mid'] },
  {
    id: 'Garen',
    name: 'Гарен',
    title: 'Сила Демасии',
    roles: ['top'],
  },
  {
    id: 'Gnar',
    name: 'Нар',
    title: 'Недостающее звено',
    roles: ['top'],
  },
  {
    id: 'Gragas',
    name: 'Грагас',
    title: 'Бражник',
    roles: ['jungle', 'top'],
  },
  {
    id: 'Graves',
    name: 'Грейвз',
    title: 'Преступник',
    roles: ['jungle'],
  },
  {
    id: 'Irelia',
    name: 'Ирелия',
    title: 'Клинок танцовщицы',
    roles: ['top', 'mid'],
  },
  {
    id: 'Janna',
    name: 'Жанна',
    title: 'Ярость бури',
    roles: ['support'],
  },
  {
    id: 'JarvanIV',
    name: 'Джарван IV',
    title: 'Образец Демасии',
    roles: ['jungle'],
  },
  { id: 'Jax', name: 'Джакс', title: 'Грандмастер', roles: ['top'] },
  { id: 'Jayce', name: 'Джейс', title: 'Защитник завтра', roles: ['top'] },
  { id: 'Jhin', name: 'Джин', title: 'Виртуоз', roles: ['adc'] },
  { id: 'Jinx', name: 'Джинкс', title: 'Шальная пушка', roles: ['adc'] },
  {
    id: 'Kaisa',
    name: "Кай'Са",
    title: 'Дочь Пустоты',
    roles: ['adc'],
  },
  {
    id: 'Kassadin',
    name: 'Кассадин',
    title: 'Странник Пустоты',
    roles: ['mid'],
  },
  {
    id: 'Katarina',
    name: 'Катарина',
    title: 'Зловещий клинок',
    roles: ['mid'],
  },
  {
    id: 'Kayn',
    name: 'Каин',
    title: 'Теневой жнец',
    roles: ['jungle'],
  },
  {
    id: 'Khazix',
    name: "Ка'Зикс",
    title: 'Охотник Пустоты',
    roles: ['jungle'],
  },
  {
    id: 'Kindred',
    name: 'Киндред',
    title: 'Вечные охотники',
    roles: ['jungle'],
  },
  { id: 'Leblanc', name: 'ЛеБлан', title: 'Обманщица', roles: ['mid'] },
  {
    id: 'LeeSin',
    name: 'Ли Син',
    title: 'Слепой монах',
    roles: ['jungle'],
  },
  {
    id: 'Leona',
    name: 'Леона',
    title: 'Лучезарный рассвет',
    roles: ['support'],
  },
  {
    id: 'Lillia',
    name: 'Лиллия',
    title: 'Робкая цветочница',
    roles: ['jungle'],
  },
  {
    id: 'Lissandra',
    name: 'Лиссандра',
    title: 'Ледяная ведьма',
    roles: ['mid'],
  },
  { id: 'Lucian', name: 'Люциан', title: 'Очиститель', roles: ['adc'] },
  { id: 'Lulu', name: 'Лулу', title: 'Фейская колдунья', roles: ['support'] },
  {
    id: 'Lux',
    name: 'Люкс',
    title: 'Леди свечения',
    roles: ['support', 'mid'],
  },
  {
    id: 'Malphite',
    name: 'Малфит',
    title: 'Каменный осколок',
    roles: ['top'],
  },
  {
    id: 'MissFortune',
    name: 'Мисс Фортуна',
    title: 'Охотница за головами',
    roles: ['adc'],
  },
  {
    id: 'Mordekaiser',
    name: 'Мордекайзер',
    title: 'Железный призрак',
    roles: ['top'],
  },
  { id: 'Morgana', name: 'Моргана', title: 'Падший ангел', roles: ['support'] },
  { id: 'Nami', name: 'Нами', title: 'Зов прилива', roles: ['support'] },
  { id: 'Nasus', name: 'Насус', title: 'Хранитель песков', roles: ['top'] },
  {
    id: 'Nautilus',
    name: 'Наутилус',
    title: 'Титан глубин',
    roles: ['support'],
  },
  {
    id: 'Nidalee',
    name: 'Нидали',
    title: 'Хищница из чащи',
    roles: ['jungle'],
  },
  { id: 'Orianna', name: 'Орианна', title: 'Леди часов', roles: ['mid'] },
  {
    id: 'Pantheon',
    name: 'Пантеон',
    title: 'Несломленный',
    roles: ['top', 'mid'],
  },
  { id: 'Pyke', name: 'Пайк', title: 'Кровь в воде', roles: ['support'] },
  { id: 'Qiyana', name: 'Кияна', title: 'Императрица стихий', roles: ['mid'] },
  { id: 'Rakan', name: 'Ракан', title: 'Обольститель', roles: ['support'] },
  { id: 'Renekton', name: 'Ренектон', title: 'Мясник песков', roles: ['top'] },
  { id: 'Riven', name: 'Ривен', title: 'Изгнанница', roles: ['top'] },
  { id: 'Samira', name: 'Самира', title: 'Роза пустыни', roles: ['adc'] },
  { id: 'Sejuani', name: 'Сеюани', title: 'Ярость Севера', roles: ['jungle'] },
  {
    id: 'Senna',
    name: 'Сенна',
    title: 'Искупительница',
    roles: ['support', 'adc'],
  },
  { id: 'Sett', name: 'Сетт', title: 'Босс', roles: ['top'] },
  { id: 'Shen', name: 'Шен', title: 'Око сумерек', roles: ['top'] },
  { id: 'Syndra', name: 'Синдра', title: 'Тёмный властелин', roles: ['mid'] },
  { id: 'Thresh', name: 'Треш', title: 'Смотритель цепей', roles: ['support'] },
  { id: 'Tristana', name: 'Тристана', title: 'Стрелок-йордл', roles: ['adc'] },
  {
    id: 'Tryndamere',
    name: 'Триндамир',
    title: 'Варварский король',
    roles: ['top'],
  },
  { id: 'TwistedFate', name: 'Твистед Фейт', title: 'Шулер', roles: ['mid'] },
  { id: 'Varus', name: 'Варус', title: 'Стрела возмездия', roles: ['adc'] },
  { id: 'Vayne', name: 'Вейн', title: 'Ночной охотник', roles: ['adc', 'top'] },
  { id: 'Viego', name: 'Виего', title: 'Погибший Король', roles: ['jungle'] },
  { id: 'Viktor', name: 'Виктор', title: 'Машинный вестник', roles: ['mid'] },
  {
    id: 'Vladimir',
    name: 'Владимир',
    title: 'Малиновый жнец',
    roles: ['mid', 'top'],
  },
  { id: 'Xayah', name: 'Ксайя', title: 'Мятежница', roles: ['adc'] },
  { id: 'Yasuo', name: 'Ясуо', title: 'Неистовый', roles: ['mid', 'adc'] },
  { id: 'Yone', name: 'Йонэ', title: 'Незабытый', roles: ['mid', 'top'] },
  { id: 'Yuumi', name: 'Юуми', title: 'Магическая кошка', roles: ['support'] },
  { id: 'Zed', name: 'Зед', title: 'Мастер теней', roles: ['mid'] },
  { id: 'Zeri', name: 'Зери', title: 'Искра Заун', roles: ['adc'] },
  { id: 'Ziggs', name: 'Зиггс', title: 'Хептеховый гремлин', roles: ['mid'] },
  {
    id: 'Zyra',
    name: 'Зайра',
    title: 'Восставшая из шипов',
    roles: ['support'],
  },
]
