import type { Player } from './index'

export const MOCK_TOP_PLAYERS: Player[] = [
  {
    id: '1',
    summonerName: 'TheShy',
    region: 'kr',
    rank: 'Challenger',
    lp: 1423,
    winRate: 67.3,
    gamesPlayed: 847,
    mainChampionId: 'Riven',
    mainChampionGamesPercent: 72,
  },
  {
    id: '2',
    summonerName: 'Agurin',
    region: 'euw',
    rank: 'Challenger',
    lp: 1356,
    winRate: 61.8,
    gamesPlayed: 1203,
    mainChampionId: 'LeeSin',
    mainChampionGamesPercent: 65,
  },
  {
    id: '3',
    summonerName: 'Drututt',
    region: 'euw',
    rank: 'Challenger',
    lp: 1289,
    winRate: 59.4,
    gamesPlayed: 956,
    mainChampionId: 'Yone',
    mainChampionGamesPercent: 58,
  },
  {
    id: '4',
    summonerName: 'KatEvolved',
    region: 'na',
    rank: 'Challenger',
    lp: 1198,
    winRate: 63.2,
    gamesPlayed: 1100,
    mainChampionId: 'Katarina',
    mainChampionGamesPercent: 81,
  },
  {
    id: '5',
    summonerName: 'Irelking',
    region: 'kr',
    rank: 'Grandmaster',
    lp: 1087,
    winRate: 58.1,
    gamesPlayed: 742,
    mainChampionId: 'Irelia',
    mainChampionGamesPercent: 77,
  },
  {
    id: '6',
    summonerName: 'Tempest',
    region: 'na',
    rank: 'Challenger',
    lp: 1045,
    winRate: 62.7,
    gamesPlayed: 634,
    mainChampionId: 'Yasuo',
    mainChampionGamesPercent: 69,
  },
  {
    id: '7',
    summonerName: 'DarkHarvest',
    region: 'ru',
    rank: 'Grandmaster',
    lp: 892,
    winRate: 57.9,
    gamesPlayed: 1450,
    mainChampionId: 'Thresh',
    mainChampionGamesPercent: 84,
  },
  {
    id: '8',
    summonerName: 'VayneSpotting',
    region: 'euw',
    rank: 'Challenger',
    lp: 1312,
    winRate: 64.5,
    gamesPlayed: 890,
    mainChampionId: 'Vayne',
    mainChampionGamesPercent: 73,
  },
]
